export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_SEARCH_ACTION = 'SET_CURRENT_SEARCH_ACTION';
export const SET_BOOKING_HISTORY = 'SET_BOOKING_HISTORY';
export const RE_FETCHING_BOOKING_HISTORY = 'RE_FETCHING_BOOKING_HISTORY';
export const DONE_FETCHING_BOOKING_HISTORY = 'DONE_FETCHING_BOOKING_HISTORY';
